<?php

namespace App\Controller;

use Cake\ORM\Exception\PersistenceFailedException;

class EditarController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function editarServico()
    {
        $response = null;
        $statusCode = 200;

        if ($this->request->is(['post', 'put', 'patch'])) {
            $data = $this->request->getData();
            $id = $data['id'] ?? null;

            if ($id === null) {
                $statusCode = 400;
                $response = ['erro' => 'ID do serviço não fornecido.'];
            } else {
                $servico = $this->Servicos->get($id);

                $servico = $this->Servicos->patchEntity($servico, $data);

                try {
                    $this->Servicos->saveOrFail($servico);
                    $response = 'Serviço editado com sucesso!';
                } catch (\Cake\ORM\Exception\PersistenceFailedException $e) {
                    $statusCode = 400;
                    $response = $e->getAttributes();
                }
            }
        }

        return $this->response
            ->withHeader('Access-Control-Allow-Origin', '*')
            ->withStatus($statusCode)
            ->withType('application/json')
            ->withStringBody(json_encode($response));
    }



}

